version: '3'

services:

  lottoserver:
    build: ./server/.
    container_name: pushserver
    ports:
      - 3002:3002

  lottoreact:
    build: ./front/.
    container_name: pushfront
    ports:
      - 3000:443
networks:
  default:
    external:
      name: docker_net