version: '3'

services:

  lottoserver:
    build: ./server/.
    container_name: pushserver
    ports:
      - 3002:3002

  lottoreact:
    build: ./front/.
    container_name: pushfront
    ports:
      - 3000:443
    volumes:
      - ./front/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./front/nginx:/etc/nginx/cert

networks:
  default:
    external:
      name: docker_net